package com.example.ui

import androidx.compose.runtime.mutableStateOf

enum class AppLanguage { DE, EN }

object StringResources {
    var currentLanguage = mutableStateOf(AppLanguage.DE)

    private val translations = mapOf(
        AppLanguage.DE to mapOf(
            "Untis Neo" to "Untis Neo",
            "Die schönere Oberfläche für deinen Schulalltag." to "Die schönere Oberfläche für deinen Schulalltag.",
            "ANMELDUNG" to "ANMELDUNG",
            "Demo-Modus aktivieren" to "Demo-Modus aktivieren",
            "Lädt die echten Screenshots-Daten zur Vorschau!" to "Zeigt echte Demodaten zur Vorschau!",
            "Bitte gib einen Benutzernamen ein oder starte den Demo-Modus!" to "Bitte Name eingeben oder Demo-Modus starten!",
            "LERNPLATZ" to "LERNPLATZ",
            "HOMEWORK" to "HAUSAUFGABEN",
            "Aufgaben offen" to "Aufgaben offen",
            "Fehlstunden (0 krank)" to "Fehlstunden (0 krank)",
            "Sprechstunden geladen." to "Sprechstunden geladen.",
            "Lehrer Sprechstunden" to "Lehrer Sprechstunden",
            "Schulferien anzeigen..." to "Schulferien anzeigen...",
            "Ferien & Feiertage" to "Ferien & Feiertage",
            "AI HAUSAUFGABEN HELFER" to "KI HAUSAUFGABEN HELFER",
            "Fotografiere dein Buch oder Arbeitsblatt, um Hausaufgaben direkt einzutragen!" to "Fotografiere dein Buch oder Arbeitsblatt, um Hausaufgaben direkt einzutragen!",
            "Gelehrtenschule" to "Gelehrtenschule",
            "Keine Stunden für diesen Tag." to "Keine Stunden für diesen Tag.",
            "NORMAL" to "NORMAL",
            "ENTFÄLLT" to "ENTFÄLLT",
            "Raumänderung" to "Raumänderung",
            "ICS KALENDERABONNEMENT" to "ICS KALENDERABO",
            "Stundenplan lokal als ICS exportiert (Cache)!" to "Stundenplan als ICS exportiert!",
            "ICS DATEI EXPORT" to "ICS DATEI EXPORT",
            "ICS Link in die Zwischenablage kopiert! Trage diesen im Google Kalender ein." to "ICS Link kopiert!",
            "ICS LINK KOPIEREN" to "ICS LINK KOPIEREN",
            "Mitteilungen" to "Mitteilungen",
            "Inhalt oder Person suchen" to "Inhalt oder Person suchen",
            "Keine Nachrichten vorhanden." to "Keine Nachrichten vorhanden.",
            "Nachricht schreiben" to "Nachricht schreiben",
            "NEUE NACHRICHT" to "NEUE NACHRICHT",
            "Bestätigen" to "Bestätigen",
            "Senden" to "Senden",
            "Hausaufgaben" to "Hausaufgaben",
            "Nur ungelöste Aufgaben" to "Nur offene",
            "Sehr schön, keine Hausaufgaben ausstehend!" to "Keine Hausaufgaben ausstehend!",
            "PRIVAT" to "PRIVAT",
            "EIGENE HAUSAUFGABE" to "EIGENE HAUSAUFGABE",
            "Abbrechen" to "Abbrechen",
            "Hinzufügen" to "Hinzufügen",
            "Notenspiegel" to "Notenverwaltung",
            "NOTENSCHNITT" to "NOTENSCHNITT",
            "Unter Berücksichtigung aller Gewichtungen" to "Unter Berücksichtigung aller Gewicht",
            "0-15 PUNKTE" to "0-15 PUNKTE",
            "1-6 SCHULNOTEN" to "1-6 SCHULNOTEN",
            "Noch keine Noten eingetragen." to "Noch keine Noten.",
            "Löschen" to "Löschen",
            "NEUE NOTE EINTRAGEN" to "NEUE NOTE",
            "Eintragen" to "Eintragen",
            "KI-Hausaufgaben" to "KI-Hausaufgaben",
            "Lade Hausaufgabenscreenshots hoch & die KI trägt sie strukturiert ein!" to "Lade Bilder hoch & die KI wertet sie aus!",
            "Analysiere Hausaufgaben mit Gemini..." to "Analysiere Hausaufgaben...",
            "Screenshot aus Galerie ausgewählt!" to "Bild ausgewählt!",
            "MOCK SCREENSHOT HOCHLADEN" to "BILD HOCHLADEN",
            "Einstellungen" to "Einstellungen",
            "API & VERBINDUNG" to "API & VERBINDUNG",
            "Einstellungen gespeichert!" to "Gespeichert!",
            "STUNDENPLAN ANSICHT" to "STUNDENPLAN",
            "Home" to "Start",
            "Timetable" to "Stundenplan",
            "Messages" to "Nachrichten",
            "Profile" to "Profil",
            "Zwangssync" to "Sync",
            "Sprache / Language" to "Sprache",
            "Wähle die App-Sprache aus" to "Wähle die App-Sprache aus"
        ),
        AppLanguage.EN to mapOf(
            "Untis Neo" to "Untis Neo",
            "Die schönere Oberfläche für deinen Schulalltag." to "The more beautiful interface for your school day.",
            "ANMELDUNG" to "LOGIN",
            "Demo-Modus aktivieren" to "Enable Demo Mode",
            "Lädt die echten Screenshots-Daten zur Vorschau!" to "Loads real mock data for preview!",
            "Bitte gib einen Benutzernamen ein oder starte den Demo-Modus!" to "Please enter a username or start Demo Mode!",
            "LERNPLATZ" to "DASHBOARD",
            "HOMEWORK" to "HOMEWORK",
            "Aufgaben offen" to "Tasks pending",
            "Fehlstunden (0 krank)" to "Absences (0 sick)",
            "Sprechstunden geladen." to "Office hours loaded.",
            "Lehrer Sprechstunden" to "Teacher Office Hours",
            "Schulferien anzeigen..." to "Show school holidays...",
            "Ferien & Feiertage" to "Holidays & Vacations",
            "AI HAUSAUFGABEN HELFER" to "AI HOMEWORK HELPER",
            "Fotografiere dein Buch oder Arbeitsblatt, um Hausaufgaben direkt einzutragen!" to "Take a picture of your book to enter homework!",
            "Gelehrtenschule" to "High School",
            "Keine Stunden für diesen Tag." to "No lessons for this day.",
            "NORMAL" to "REGULAR",
            "ENTFÄLLT" to "CANCELLED",
            "Raumänderung" to "Room change",
            "ICS KALENDERABONNEMENT" to "ICS CALENDAR SYNC",
            "Stundenplan lokal als ICS exportiert (Cache)!" to "Timetable exported as ICS!",
            "ICS DATEI EXPORT" to "EXPORT ICS FILE",
            "ICS Link in die Zwischenablage kopiert! Trage diesen im Google Kalender ein." to "ICS link copied! Add it to Google Calendar.",
            "ICS LINK KOPIEREN" to "COPY ICS LINK",
            "Mitteilungen" to "Messages",
            "Inhalt oder Person suchen" to "Search content or person",
            "Keine Nachrichten vorhanden." to "No messages available.",
            "Nachricht schreiben" to "Write message",
            "NEUE NACHRICHT" to "NEW MESSAGE",
            "Bestätigen" to "Confirm",
            "Senden" to "Send",
            "Hausaufgaben" to "Homework",
            "Nur ungelöste Aufgaben" to "Unsolved only",
            "Sehr schön, keine Hausaufgaben ausstehend!" to "Great, no pending homework!",
            "PRIVAT" to "PRIVATE",
            "EIGENE HAUSAUFGABE" to "OWN HOMEWORK",
            "Abbrechen" to "Cancel",
            "Hinzufügen" to "Add",
            "Notenspiegel" to "Grades",
            "NOTENSCHNITT" to "GPA AVG",
            "Unter Berücksichtigung aller Gewichtungen" to "Considering all weights",
            "0-15 PUNKTE" to "0-15 POINTS",
            "1-6 SCHULNOTEN" to "1-6 GRADES",
            "Noch keine Noten eingetragen." to "No grades yet.",
            "Löschen" to "Delete",
            "NEUE NOTE EINTRAGEN" to "ENTER NEW GRADE",
            "Eintragen" to "Save",
            "KI-Hausaufgaben" to "AI Homework",
            "Lade Hausaufgabenscreenshots hoch & die KI trägt sie strukturiert ein!" to "Upload images and AI will parse them!",
            "Analysiere Hausaufgaben mit Gemini..." to "Analyzing homework...",
            "Screenshot aus Galerie ausgewählt!" to "Image selected!",
            "MOCK SCREENSHOT HOCHLADEN" to "UPLOAD MOCK IMAGE",
            "Einstellungen" to "Settings",
            "API & VERBINDUNG" to "API & CONNECTION",
            "Einstellungen gespeichert!" to "Settings saved!",
            "STUNDENPLAN ANSICHT" to "TIMETABLE VIEW",
            "Home" to "Home",
            "Timetable" to "Timetable",
            "Messages" to "Messages",
            "Profile" to "Profile",
            "Zwangssync" to "Sync",
            "Sprache / Language" to "Language",
            "Wähle die App-Sprache aus" to "Select App Language"
        )
    )

    fun get(key: String): String {
        return translations[currentLanguage.value]?.get(key) ?: key
    }
}
